name: .NET

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: Accessories_PC_Nik.Api
      run: dotnet restore 
      
    - name: Build
      working-directory: Accessories_PC_Nik.Api
      run: dotnet build --configuration Debug --no-restore
      
    - name: Test Repository
      working-directory: Accessories_PC_Nik.Repositories.Tests
      run: dotnet test

    - name: Test Service
      working-directory: Accessories_PC_Nik.Services.Tests
      run: dotnet test
      
    - name: Test Api
      working-directory: Accessories_PC_Nik.Api.Tests
      run: dotnet test
